FROM docker.io/library/maven:3-eclipse-temurin-8 AS builder

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.m2 \
    set -eux; \
    find /root/.m2/repository -type f -size 0 -delete; \
    xml_api_jar=/root/.m2/repository/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar; \
    install -d "$(dirname "$xml_api_jar")"; \
    curl --fail --location --retry 3 \
      --output "$xml_api_jar.download" \
      https://repo.maven.apache.org/maven2/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar; \
    echo "d0b4887dc34d57de49074a58affad439a013d0baffa1a8034f8ef2a5ea191646  $xml_api_jar.download" \
      | sha256sum --check -; \
    mv "$xml_api_jar.download" "$xml_api_jar"; \
    mvn clean package -DskipTests; \
    # Copy WARs to root for multi-stage build pickup
    # Use glob to handle version-suffixed filenames
    cp web/target/LibreClinica-web*.war /LibreClinica-web.war; \
    cp ws/target/LibreClinica-ws*.war /LibreClinica-ws.war;

############################################################
FROM tomcat:9-jdk11

# `postgresql-client` is here for pg_isready only (see the wait-for-db script
# below). It is deliberately NOT a plain TCP probe: during postgres crash
# recovery the port is already LISTENing and accepts a socket, but the server
# answers "the database system is starting up" — which is exactly the state that
# killed both webapps on 2026-08-29 (LOG-2). pg_isready distinguishes the two
# (exit 0 = accepting, 1 = rejecting/starting up, 2 = no response).
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends wget postgresql-client; \
    rm -rf /var/lib/apt/lists/*; \
    # set up redirection to application when accessing tomcat root
    mkdir /usr/local/tomcat/webapps/ROOT; \
    echo '<html><head><meta http-equiv="refresh" content="0; URL=libreclinica/" /></head></html>' \
        > /usr/local/tomcat/webapps/ROOT/index.html;

# set up volumes for data and logs
VOLUME \
    /usr/local/tomcat/libreclinica.data \
    /usr/local/tomcat/logs

# add config files
COPY \
    /docker/config/ \
    /usr/local/tomcat/libreclinica.config/

COPY docker/entrypoint.sh /usr/local/bin/libreclinica-entrypoint
RUN sed -i 's/\r$//' /usr/local/bin/libreclinica-entrypoint \
    && chmod +x /usr/local/bin/libreclinica-entrypoint

# ============================================================================
# LOG-2 — wait for postgres to ACCEPT connections before Tomcat starts
# ----------------------------------------------------------------------------
# Failure this prevents (observed 2026-08-29 15:03, container stayed broken for
# two days): a Docker-daemon/host restart starts every `restart: always`
# container concurrently. compose's `depends_on: condition: service_healthy`
# orders `docker compose up` ONLY — it does not order a daemon restart. Postgres
# went into ~10s of crash recovery; LibreClinica's Spring ContextLoaderListener
# has no DBCP connect retry, so it threw
#   "Cannot create PoolableConnectionFactory (FATAL: the database system is
#    starting up)"
# and Tomcat marked BOTH contexts (/libreclinica and /libreclinica-ws) as
# "startup failed". Tomcat never redeploys a failed context, so the process
# stayed UP with two dead webapps and only the healthcheck noticed (404s).
#
# This script turns that race into a slow start instead of a dead context. It is
# generated inline rather than COPY'd so that adding it does not change the build
# context (`.dockerignore` allow-lists what the builder stage copies), i.e. the
# Maven stage stays cached.
#
# Knobs (env, both optional): DB_WAIT_TIMEOUT_SECONDS (default 300),
# DB_WAIT_INTERVAL_SECONDS (default 2). Exceeding the timeout EXITS NON-ZERO on
# purpose — a container that dies is restarted by Docker and gets another go,
# which is strictly better than a Tomcat that lives on with dead contexts.
# ============================================================================
RUN set -eux; \
    printf '%s\n' \
      '#!/bin/sh' \
      '# Generated by the LibreClinicaCore Dockerfile (LOG-2). Waits until' \
      '# postgres is ACCEPTING connections, then execs the real entrypoint.' \
      'set -u' \
      '' \
      'host=${dbHost:-db}' \
      'port=${dbPort:-5432}' \
      'user=${dbUser:-postgres}' \
      'name=${dbName:-${db:-libreclinica}}' \
      'limit=${DB_WAIT_TIMEOUT_SECONDS:-300}' \
      'step=${DB_WAIT_INTERVAL_SECONDS:-2}' \
      '' \
      'streak=0' \
      'waited=0' \
      'echo "[wait-for-db] waiting for ${host}:${port}/${name} (timeout ${limit}s)"' \
      'while [ "$waited" -lt "$limit" ]; do' \
      '  if pg_isready -h "$host" -p "$port" -U "$user" -d "$name" >/dev/null 2>&1; then' \
      '    streak=$((streak + 1))' \
      '    # Two consecutive successes: one lone OK can still be the instant' \
      '    # before postgres re-enters recovery on a resumed host.' \
      '    if [ "$streak" -ge 2 ]; then break; fi' \
      '  else' \
      '    streak=0' \
      '  fi' \
      '  sleep "$step"' \
      '  waited=$((waited + step))' \
      'done' \
      '' \
      'if [ "$streak" -lt 2 ]; then' \
      '  echo "[wait-for-db] FATAL: ${host}:${port}/${name} was not accepting connections after ${limit}s" >&2' \
      '  exit 1' \
      'fi' \
      '' \
      'echo "[wait-for-db] database ready after ${waited}s — starting Tomcat"' \
      'exec "$@"' \
      > /usr/local/bin/libreclinica-wait-for-db; \
    chmod +x /usr/local/bin/libreclinica-wait-for-db; \
    sh -n /usr/local/bin/libreclinica-wait-for-db

# add LibreClinica web application WAR (context path: /libreclinica)
COPY --from=builder \
    /LibreClinica-web.war \
    /usr/local/tomcat/webapps/libreclinica.war

# add LibreClinica SOAP web services WAR (context path: /libreclinica-ws)
# This provides SOAP endpoints at /libreclinica-ws/ws/{service}/v1
COPY --from=builder \
    /LibreClinica-ws.war \
    /usr/local/tomcat/webapps/libreclinica-ws.war

# wait-for-db → property rewrite → Tomcat. Each link execs the next, so PID 1 is
# still catalina.sh and signal handling is unchanged.
ENTRYPOINT ["/usr/local/bin/libreclinica-wait-for-db", "/usr/local/bin/libreclinica-entrypoint"]
CMD ["catalina.sh", "run"]
